/// Every word the interface says (S19). The vocabulary is an enum rather than free-form
/// strings so the suite can walk it: a key missing from a language, or a placeholder that
/// changed shape, fails the build instead of reaching a user as a blank label.
public enum UIText: String, CaseIterable, Sendable {
    case appName = "app.name"

    case menuGrantAccessibility = "menu.grantAccessibility"
    case menuOpenInputMonitoring = "menu.openInputMonitoring"
    case menuSettings = "menu.settings"
    case menuCopyInventory = "menu.copyInventory"
    case menuQuit = "menu.quit"

    case permissionBlocked = "permission.blocked"
    case permissionRefused = "permission.refused"
    case permissionDeaf = "permission.deaf"
    case permissionObserving = "permission.observing"

    case settingsTitle = "settings.title"
    case settingsGeneral = "settings.tab.general"
    case settingsAppearance = "settings.tab.appearance"

    case generalApplications = "general.applications"
    case generalFrontWindows = "general.frontWindows"
    case generalScreen = "general.screen"
    case generalRevealDelay = "general.revealDelay"
    case generalOpenAtLogin = "general.openAtLogin"
    case generalPrivateLayer = "general.privateLayer"
    case generalPrivateLayerNote = "general.privateLayerNote"
    case generalWindowSwitching = "general.windowSwitching"
    case generalLanguage = "general.language"
    case generalLanguageSystem = "general.languageSystem"
    case loginItemPending = "general.loginItemPending"
    case loginItemRefused = "general.loginItemRefused"
    case screenFocused = "screen.focused"
    case screenPointer = "screen.pointer"

    case shortcutRecording = "shortcut.recording"
    case shortcutCancelHint = "shortcut.cancelHint"
    case shortcutPermission = "shortcut.permission"
    case shortcutGrant = "shortcut.grant"
    case shortcutRestore = "shortcut.restore"
    case shortcutUnnamedKey = "shortcut.unnamedKey"
    case rejectNoModifier = "reject.noModifier"
    case rejectContainsShift = "reject.containsShift"
    case rejectEscape = "reject.escape"
    case rejectReserved = "reject.reserved"
    case rejectModifierKey = "reject.modifierKey"
    case rejectTaken = "reject.taken"

    case appearanceProfile = "appearance.profile"
    case appearanceBuiltIn = "appearance.builtIn"
    case appearanceName = "appearance.name"
    case appearanceNamePlaceholder = "appearance.namePlaceholder"
    case appearanceDuplicate = "appearance.duplicate"
    case appearanceDelete = "appearance.delete"
    case appearanceFull = "appearance.full"
    case appearanceIconSize = "appearance.iconSize"
    case appearanceRibbonPadding = "appearance.ribbonPadding"
    case appearanceGap = "appearance.gap"
    case appearanceCornerRadius = "appearance.cornerRadius"
    case appearanceFrameWidth = "appearance.frameWidth"
    case appearanceFramePadding = "appearance.framePadding"
    case appearanceBackground = "appearance.background"
    case appearanceCarousel = "appearance.carousel"
    case appearanceCarouselTurns = "appearance.carouselTurns"
    case appearanceSlots = "appearance.slots"
    case appearanceSelection = "appearance.selection"
    case appearanceSample = "appearance.sample"

    case backgroundGlass = "background.glass"
    case backgroundTransparent = "background.transparent"
    case backgroundSolid = "background.solid"
    case backgroundShade = "background.shade"
    case backgroundOpacity = "background.opacity"

    case selectionNative = "selection.native"
    case selectionEnlarged = "selection.enlarged"
    case selectionSpotlight = "selection.spotlight"
    case selectionFramed = "selection.framed"

    case unitPoints = "unit.points"
    case unitPercent = "unit.percent"
    case unitSlots = "unit.slots"
    case unitMilliseconds = "unit.milliseconds"

    case previewCount = "preview.count"
    case previewShow = "preview.show"
    case previewDone = "preview.done"
    case previewEntry = "preview.entry"

    case ribbonEmpty = "ribbon.empty"
}
